---
kind: BareMetalHost
apiVersion: metal3.io/v1alpha1
metadata:
  name: 2m25300d3h
spec:
  online: true
  # bootMACAddress: 50:65:f3:6e:00:1a # 10gb-port1
  # bootMACAddress: 50:65:f3:6e:00:1b # 10gb-port2
  # bootMACAddress: 50:65:f3:6e:00:1c # iLO
  bootMACAddress: 8c:dc:d4:0f:16:d8 # 10gb-port1
  # bootMACAddress: 8c:dc:d4:0f:16:dc # 10gb-port2
  bootMode: legacy
  bmc:
    address: ilo4-virtualmedia://2m25300d3h.ilo.metal.suse.network
    credentialsName: 2m25300d3h-credentials
  # externallyProvisioned: true
  image:
    url: https://media.metal.suse.network/elemental.iso
    format: live-iso
  userData:
    namespace: ilo
    name: 2m25300d3h-user-data
