{{- if .Values.global.enable_ironic -}}
apiVersion: v1
kind: Secret
metadata:
  name: ironic-mariadb
  labels:
    {{- include "ironic.labels" . | nindent 4 }}
type: Opaque    
data:
  password: {{ .Values.baremetaloperator.mariadbPassword | toString | b64enc }}
{{- end -}}
